// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package parser

import (
	"errors"
	"fmt"
)

const (
	// FieldTypeString is a FieldType of type String.
	FieldTypeString FieldType = iota
	// FieldTypeInt is a FieldType of type Int.
	FieldTypeInt
	// FieldTypeFloat is a FieldType of type Float.
	FieldTypeFloat
	// FieldTypeBool is a FieldType of type Bool.
	FieldTypeBool
	// FieldTypeList is a FieldType of type List.
	FieldTypeList
)

var ErrInvalidFieldType = errors.New("not a valid FieldType")

const _FieldTypeName = "stringintfloatboollist"

var _FieldTypeMap = map[FieldType]string{
	FieldTypeString: _FieldTypeName[0:6],
	FieldTypeInt:    _FieldTypeName[6:9],
	FieldTypeFloat:  _FieldTypeName[9:14],
	FieldTypeBool:   _FieldTypeName[14:18],
	FieldTypeList:   _FieldTypeName[18:22],
}

// String implements the Stringer interface.
func (x FieldType) String() string {
	if str, ok := _FieldTypeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("FieldType(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x FieldType) IsValid() bool {
	_, ok := _FieldTypeMap[x]
	return ok
}

var _FieldTypeValue = map[string]FieldType{
	_FieldTypeName[0:6]:   FieldTypeString,
	_FieldTypeName[6:9]:   FieldTypeInt,
	_FieldTypeName[9:14]:  FieldTypeFloat,
	_FieldTypeName[14:18]: FieldTypeBool,
	_FieldTypeName[18:22]: FieldTypeList,
}

// ParseFieldType attempts to convert a string to a FieldType.
func ParseFieldType(name string) (FieldType, error) {
	if x, ok := _FieldTypeValue[name]; ok {
		return x, nil
	}
	return FieldType(0), fmt.Errorf("%s is %w", name, ErrInvalidFieldType)
}

// MarshalText implements the text marshaller method.
func (x FieldType) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *FieldType) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseFieldType(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *FieldType) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
